# Default values for cover-service-importers.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

env: "prod"

ingress:
  enabled: true
  enableAuth: false
  enableTLS: false
  path: "/"

app:
  image:
    version: latest
    pullPolicy: IfNotPresent
  redis:
    server: "redis"
    port: "6379"
    cache_db: "11"
  db:
    server: "cover-service-prod-database.mariadb.database.azure.com"
    port: "3306"
    database: "upload"
  storage:
    class: "azurefile-premium"
    size: "100Gi"
    access: "ReadWriteMany"
  php:
    memory_limit: "128M"
    max_children: "80"
    start_servers: "15"
    min_spare_servers: "15"
    max_spare_servers: "30"
    slowlog_timeout: "1"
    post_max_size: "56M"
    upload_max_filesize: "48M"

nginx:
  exporter:
    image:
      version: 0.6.0