api_platform:
    title: 'DDB Cover Service Upload'
    version: '1.0.0'
    description: >-
        This service allows for uploading covers for library materials indexed by isbn, issn, faust, pid. Uploaded
        covers become available on [DDB Cover Service](https://cover.dandigbib.org/).

        The service is provided by [Danskernes Digitale Bibliotek](https://www.danskernesdigitalebibliotek.dk/)

        ### Authentication notes

        Authentication is done via OAuth2 against auth.dbc.dk. To obtain a valid token follow the instructions
        here: [Open Platform](https://openplatform.dbc.dk/v3/).
        To use the "Authorize" option in this tool use your 'client_id' and 'client_secret' and fill in '@' for
        both username and password.

    show_webby: false
    enable_re_doc: false
    formats:
        json:
            mime_types: ['application/json']
        html:
            mime_types: ['text/html']

    mapping:
        paths: ['%kernel.project_dir%/src/Entity']

    collection:
        pagination:
            enabled: false

    patch_formats:
        json: ['application/merge-patch+json']

    swagger:
        versions: [3]

    oauth:
        enabled: true
        type: 'oauth2'
        flow: 'password'
        tokenUrl: 'https://login.bib.dk/oauth/token'
