framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            async_priority_high:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: high
                    queues:
                        cs_high: ~

            #failed: 'doctrine://default?queue_name=failed'

        routing:
            'App\Message\CoverUserUploadMessage': async_priority_high
