framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            # Should match queue name in cover service importers.
            cover-store-queue:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: coverstore

            #failed: 'doctrine://default?queue_name=failed'

        routing:
            'App\Message\CoverUserUploadMessage': cover-store-queue
