framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async_priority_high:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: high
                        type: fanout
                    queues:
                        cs_high: ~

            failed:
                dsn: '%env(MESSENGER_TRANSPORT_DSN_FAILED)%'
                options:
                    auto_setup: 'false'

        routing:
            # Route your messages to the transports
            'App\Message\CoverUserUploadMessage': async_priority_high

        buses:
            messenger.bus.default:
                middleware:
                    - 'messenger.middleware.reject_redelivered_message_middleware'
