vich_uploader:
    db_driver: orm

    mappings:
        cover:
            uri_prefix: /cover
            upload_destination: '%kernel.project_dir%/public/cover'
            namer: Vich\UploaderBundle\Naming\OrignameNamer