openapi: 3.0.3
info:
  title: 'DDF Cover Service Upload'
  description: |-
    This service allows for uploading covers for library materials indexed by isbn, issn, faust, pid. Uploaded covers become available on [DDB Cover Service](https://cover.dandigbib.org/).
    The service is provided by [Det Digitale Folkebibliotek](https://detdigitalefolkebibliotek.dk/section/i-brug-paa-biblioteket/cover-service)
    ### Authentication notes
    Authentication is done via OAuth2 against auth.dbc.dk. To obtain a valid token follow the instructions here: [Open Platform](https://openplatform.dbc.dk/v3/). To use the "Authorize" option in this tool use your 'client_id' and 'client_secret' and fill in '@agency' (e.g. '@123456') for both username and password.
  version: 1.0.0
servers:
  -
    url: /
    description: ''
paths:
  /api/covers:
    get:
      operationId: getCoverCollection
      tags:
        - Cover
      responses:
        200:
          description: 'Cover collection'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Cover-Read'
            text/html:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Cover-Read'
      summary: 'Retrieves the collection of Cover resources.'
      description: 'Retrieves the collection of Cover resources.'
      parameters: []
      deprecated: false
    post:
      operationId: postCoverCollection
      tags:
        - Cover
      responses:
        201:
          description: 'Cover resource created'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cover-Read'
            text/html:
              schema:
                $ref: '#/components/schemas/Cover-Read'
          links:
            GetCoverItem:
              operationId: getCoverItem
              parameters:
                id: '$response.body#/id'
              description: 'The `id` value returned in the response can be used as the `id` parameter in `GET /api/covers/{id}`.'
        400:
          description: 'Invalid input'
        422:
          description: 'Unprocessable entity'
      summary: 'Creates a Cover resource.'
      description: 'Creates a Cover resource.'
      parameters: []
      requestBody:
        description: ''
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                cover:
                  type: string
                  format: binary
        required: false
      deprecated: false
    parameters: []
  '/api/covers/{id}':
    get:
      operationId: getCoverItem
      tags:
        - Cover
      responses:
        200:
          description: 'Cover resource'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cover-Read'
            text/html:
              schema:
                $ref: '#/components/schemas/Cover-Read'
        404:
          description: 'Resource not found'
      summary: 'Retrieves a Cover resource.'
      description: 'Retrieves a Cover resource.'
      parameters:
        -
          name: id
          in: path
          description: 'Resource identifier'
          required: true
          deprecated: false
          allowEmptyValue: false
          schema:
            type: string
          style: simple
          explode: false
          allowReserved: false
      deprecated: false
    parameters: []
  /api/materials:
    get:
      operationId: getMaterialCollection
      tags:
        - Material
      responses:
        200:
          description: 'Material collection'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Material-Read'
            text/html:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Material-Read'
      summary: 'Retrieves the collection of Material resources.'
      description: 'Retrieves the collection of Material resources.'
      parameters: []
      deprecated: false
    post:
      operationId: postMaterialCollection
      tags:
        - Material
      responses:
        201:
          description: 'Material resource created'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Material-Read'
            text/html:
              schema:
                $ref: '#/components/schemas/Material-Read'
          links:
            GetMaterialItem:
              operationId: getMaterialItem
              parameters:
                id: '$response.body#/id'
              description: 'The `id` value returned in the response can be used as the `id` parameter in `GET /api/materials/{id}`.'
        400:
          description: 'Invalid input'
        422:
          description: 'Unprocessable entity'
      summary: 'Creates a Material resource.'
      description: 'Creates a Material resource.'
      parameters: []
      requestBody:
        description: 'The new Material resource'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Material-Write'
          text/html:
            schema:
              $ref: '#/components/schemas/Material-Write'
        required: true
      deprecated: false
    parameters: []
  '/api/materials/{id}':
    get:
      operationId: getMaterialItem
      tags:
        - Material
      responses:
        200:
          description: 'Material resource'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Material-Read'
            text/html:
              schema:
                $ref: '#/components/schemas/Material-Read'
        404:
          description: 'Resource not found'
      summary: 'Retrieves a Material resource.'
      description: 'Retrieves a Material resource.'
      parameters:
        -
          name: id
          in: path
          description: 'Resource identifier'
          required: true
          deprecated: false
          allowEmptyValue: false
          schema:
            type: string
          style: simple
          explode: false
          allowReserved: false
      deprecated: false
    delete:
      operationId: deleteMaterialItem
      tags:
        - Material
      responses:
        204:
          description: 'Material resource deleted'
        404:
          description: 'Resource not found'
      summary: 'Removes the Material resource.'
      description: 'Removes the Material resource.'
      parameters:
        -
          name: id
          in: path
          description: 'Resource identifier'
          required: true
          deprecated: false
          allowEmptyValue: false
          schema:
            type: string
          style: simple
          explode: false
          allowReserved: false
      deprecated: false
    parameters: []
components:
  schemas:
    Cover-Read:
      type: object
      description: ''
      externalDocs:
        url: 'https://schema.org/MediaObject'
      properties:
        id:
          readOnly: true
          type: integer
        imageUrl:
          type: string
          format: url
          example: 'https://upload.cover.dandigbib.org/cover/5ed65baa2b264_870970-basis%3A52890365.jpg'
          externalDocs:
            url: 'https://schema.org/contentUrl'
        size:
          type: integer
          example: 769822
          nullable: true
        agencyId:
          type: string
          example: '123456'
    Material-Read:
      type: object
      description: ''
      properties:
        id:
          readOnly: true
          type: integer
        isIdentifier:
          type: string
          example: '870970-basis:29862885'
        isType:
          type: string
          enum:
            - faust
            - isbn
            - issn
            - pid
          example: pid
        agencyId:
          type: string
          example: '123456'
        cover:
          type: object
          example:
            id: 1
            imageUrl: 'https://upload.cover.dandigbib.org/cover/5ed65baa2b264_870970-basis%3A52890365.jpg'
            size: 1478312
            agencyId: '123456'
          externalDocs:
            url: 'https://schema.org/image'
          nullable: true
          anyOf:
            -
              $ref: '#/components/schemas/Cover-Read'
    Material-Write:
      type: object
      description: ''
      properties:
        isIdentifier:
          type: string
          example: '870970-basis:29862885'
        isType:
          type: string
          enum:
            - faust
            - isbn
            - issn
            - pid
          example: pid
        cover:
          type: object
          example:
            id: 1
            imageUrl: 'https://upload.cover.dandigbib.org/cover/5ed65baa2b264_870970-basis%3A52890365.jpg'
            size: 1478312
            agencyId: '123456'
          externalDocs:
            url: 'https://schema.org/image'
          format: iri-reference
          nullable: true
  responses: {  }
  parameters: {  }
  examples: {  }
  requestBodies: {  }
  headers: {  }
  securitySchemes:
    oauth:
      type: oauth2
      description: 'OAuth 2.0 password Grant'
      flows:
        password:
          tokenUrl: 'https://login.bib.dk/oauth/token'
          scopes: {  }
security:
  -
    oauth: []
tags: []
