---
apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-cronjob
spec:
  schedule: {{ .Values.cron.runAt | quote }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: {{ .Values.cron.successfulLimit }}
  failedJobsHistoryLimit: {{ .Values.cron.failedLimit }}
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        spec:
          containers:
            - name: cronjob
              image: danskernesdigitalebibliotek/cover-service-upload:{{ .Values.app.image.version }}
              imagePullPolicy: {{ .Values.app.image.imagePullPolicy }}
              args:
                - "bin/console"
                - "app:image:cleanup"
                - "--no-debug"
              volumeMounts:
                - mountPath: /var/www/html/public/cover
                  name: public-covers-data
              env:
                - name: APP_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Release.Name }}-secret
                      key: APP_SECRET
                - name: APP_DB_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Release.Name }}-secret
                      key: APP_DB_USERNAME
                - name: APP_DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Release.Name }}-secret
                      key: APP_DB_PASSWORD
                - name: APP_OPENPLATFORM_ID
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Release.Name }}-secret
                      key: APP_OPENPLATFORM_ID
                - name: APP_OPENPLATFORM_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Release.Name }}-secret
                      key: APP_OPENPLATFORM_SECRET
                - name: APP_AMQP_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Release.Name }}-secret
                      key: APP_AMQP_USERNAME
                - name: APP_AMQP_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Release.Name }}-secret
                      key: APP_AMQP_PASSWORD
                - name: APP_CLOUDINARY_ID
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Release.Name }}-secret
                      key: APP_CLOUDINARY_ID
                - name: APP_CLOUDINARY_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Release.Name }}-secret
                      key: APP_CLOUDINARY_SECRET
                - name: APP_CLOUDINARY_DOMAIN
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Release.Name }}-secret
                      key: APP_CLOUDINARY_DOMAIN
              envFrom:
                - configMapRef:
                    name: {{ .Release.Name }}-configmap
          volumes:
            - name: public-covers-data
              persistentVolumeClaim:
                claimName: uploaded-covers-managed-disk
          restartPolicy: OnFailure
