---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-configmap
data:
  APP_DB_SERVER: {{ .Values.app.db.server | quote }}
  APP_DB_PORT: {{ .Values.app.db.port | quote }}
  APP_DB_DATABASE: {{ .Values.app.db.database | quote }}
  APP_DB_VERSION: {{ .Values.app.db.version | quote }}
  APP_REDIS_SERVER: {{ .Values.app.redis.server | quote }}
  APP_REDIS_PORT: {{ .Values.app.redis.port | quote }}
  APP_REDIS_CACHE_SERVER: {{ .Values.app.redis.server | quote }}
  APP_REDIS_CACHE_PORT: {{ .Values.app.redis.port | quote }}
  APP_REDIS_CACHE_DB: {{ .Values.app.redis.cache_db | quote }}
  APP_REDIS_CACHE_PREFIX: {{ .Values.app.redis.prefix | quote }}
  APP_AMQP_SERVER: {{ .Values.app.amqp.server | quote }}
  APP_AMQP_PORT: {{ .Values.app.amqp.port | quote }}
  APP_DEFAULT_URI: {{ .Values.ingress.domain | quote }}
  APP_CLOUDINARY_FOLDER: {{ .Values.app.coverstore.folder | quote }}
  PHP_MEMORY_LIMIT: {{ .Values.app.php.memory_limit | quote }}
  PHP_PM_MAX_CHILDREN: {{ .Values.app.php.max_children | quote }}
  PHP_PM_START_SERVERS: {{ .Values.app.php.start_servers | quote }}
  PHP_PM_MIN_SPARE_SERVERS: {{ .Values.app.php.min_spare_servers | quote }}
  PHP_PM_MAX_SPARE_SERVERS: {{ .Values.app.php.max_spare_servers | quote }}
  PHP_REQUEST_SLOWLOG_TIMEOUT: {{ .Values.app.php.slowlog_timeout | quote }}
  PHP_POST_MAX_SIZE: {{ .Values.app.php.post_max_size | quote }}
  PHP_UPLOAD_MAX_FILESIZE: {{ .Values.app.php.upload_max_filesize | quote }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-nginx-config
data:
  PHP_FPM_SERVER: "127.0.0.1"
  PHP_FPM_SERVER_PORT: "9000"
  PHP_FPM_CLIENT_MAX_BODY_SIZE: {{ .Values.app.php.upload_max_filesize | quote }}
