# Import settings from 'prod' to match that env.
imports:
    - { resource: '../prod/' }

# Overwrite prod cache settings. Redis not available when building on Github.
framework:
    cache:
        system: cache.adapter.filesystem
        app: cache.adapter.system

    pools:
        token.cache:
            adapter: cache.adapter.system
